"""Corrupt a valid chain — ``python -m cracy_certval.invalidate``.

The core of the toolkit. It takes certificate material a product actually
uses — the chain that signs its firmware, or authenticates its TLS endpoint —
confirms that chain is genuinely valid, and then derives from it a battery of
chains that are valid in every respect except one deliberately introduced
defect. Those chains are the test material: a correctly implemented product
must reject every one of them, and accepting even a single one is a finding.
"""

import argparse
import os
import shutil

from .certs import cert_sha256
from .chains import build_paths, find_root, verify_chain
from .loading import (
    Pkcs12Reader,
    collect_material,
    resolve_base_dir,
    write_key_dir,
)
from .openssl import debug, require_openssl
from .pinning import read_pin, resolve_pin_path, verify_pin
from .scenarios import (
    EXPORT_DIR,
    POSITION_SCENARIOS,
    SCENARIO_ALIASES,
    SCENARIO_MENU,
    SCENARIOS,
    apply_scenario,
    save_chain,
)


def find_trusted_chain(certs: list, pinned_hash: str = None):
    """The first buildable path that verifies and matches the pin.

    Returns ``(chain, candidate_count)``. Every candidate is tried because a
    bundle may contain several plausible paths — cross-signed CAs, or an old
    and a new intermediate — and only one of them may be the trusted one.
    """
    candidates = build_paths(certs)

    if not candidates:
        raise SystemExit("ERROR: No chain found")

    for candidate in candidates:
        root = find_root(candidate)

        if root is None:
            debug("Candidate rejected: no root certificate")
            continue

        if pinned_hash is not None and not verify_pin(root, pinned_hash):
            debug(
                f"Candidate rejected: root {cert_sha256(root)[:16]}… "
                f"does not match the pin"
            )
            continue

        verified, output = verify_chain(candidate)

        if not verified:
            debug(f"Candidate rejected by openssl verify: {output}")
            continue

        return candidate, len(candidates)

    raise SystemExit("ERROR: No trusted valid chain")


def collect_keys(paths: list, pin_path: str, pkcs12: Pkcs12Reader) -> list:
    """Private keys from the inputs, plus any sibling ``keys/`` directory.

    A chain generated by this toolkit keeps its keys in a ``keys/`` folder
    beside the certificates, so pointing the invalidator at the chain alone
    is enough to reach the scenarios that need to re-sign.
    """
    _, keys = collect_material(paths, pkcs12)

    base_dir = resolve_base_dir(paths, pin_path)
    sibling = os.path.join(base_dir, "keys")

    if os.path.isdir(sibling):
        _, more = collect_material([sibling], pkcs12)
        keys += more

    return keys


# Command line

HELP_DESCRIPTION = """\
Corrupt a valid certificate chain into test chains that each contain exactly
one defect. Any input supplied on the command line is not prompted for;
supply them all and the run is fully non-interactive.\
"""

HELP_EPILOG = """\
inputs (prompted only when the option is omitted):
  PATH...               one or more certificate paths
  -s LIST               scenario numbers or names, comma-separated
                        (e.g. 1,2,5 or expired_server,corrupted_server)
                        or 'all'
  -p LIST               scenarios 3, 4 and 5 only: which intermediate(s)
                        to target (e.g. 1,2).  Pass -p '' to target none.

examples:
  cracy-cert-invalidate                              prompt for everything
  cracy-cert-invalidate valid_chain_*/               prompt for scenarios
  cracy-cert-invalidate valid_chain_*/ -s all -p 1,2 no prompts
  cracy-cert-invalidate chain.pem -s 2,6             no prompts (neither
                                                     scenario uses -p)

scenarios:
  1  expired_server           re-sign leaf as expired
  2  corrupted_server         mangle the leaf PEM body
  3  expired_intermediate     re-sign an intermediate as expired
  4  non_ca_intermediate      re-sign an intermediate with CA:FALSE
  5  missing_intermediate     drop an intermediate from the chain
  6  root_hash_mismatch       valid chain, wrong root_hash.txt
  7  root_hash_not_checked    valid chain, no pin file
  8  expired_root             re-sign the root as expired

  Scenarios 1, 3, 4 and 8 need the relevant private key and are skipped
  when it cannot be found.

output:
  invalid_chain/<scenario_name>/[int<N>/]

environment:
  DEBUG_CERT_CHAIN=1      print the openssl commands being run
  CRACY_P12_PASSWORD      password for encrypted PKCS#12 inputs; preferred
                          over --p12-password, which is visible in the shell
                          history and process list
"""


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        prog="cracy-cert-invalidate",
        description=HELP_DESCRIPTION,
        epilog=HELP_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "paths",
        nargs="*",
        metavar="PATH",
        help=(
            "Certificate path(s) — files or directories; "
            "prompted for if omitted"
        ),
    )

    parser.add_argument(
        "-s", "--scenarios",
        default=None,
        metavar="LIST",
        help=(
            "Comma-separated scenario numbers or names, or 'all'; "
            "prompted for if omitted"
        ),
    )

    parser.add_argument(
        "-p", "--positions",
        default=None,
        metavar="LIST",
        help=(
            "Comma-separated intermediate positions for scenarios 3, 4 and "
            "5; prompted for if omitted and such a scenario is selected"
        ),
    )

    parser.add_argument(
        "--p12-password",
        default=None,
        metavar="PASSWORD",
        help=(
            "Password for encrypted PKCS#12 inputs. Prefer the "
            "CRACY_P12_PASSWORD environment variable — an argument is "
            "visible in the shell history and process list."
        ),
    )

    return parser.parse_args(argv)


# Each resolver takes the command-line value and only falls back to a prompt
# when it was not supplied, so a fully specified invocation never blocks. The
# parse_* helpers hold the validation, so command-line values can be checked
# up front, before the expensive chain building.

def resolve_paths(paths):
    if not paths:
        paths = input("Enter certificate path(s): ").strip().split()

    if not paths:
        raise SystemExit("ERROR: No input provided")

    return paths


def parse_scenarios(raw):
    raw = raw.strip().lower()

    if raw == "all":
        return list(SCENARIOS)

    choices = []
    invalid = []

    for token in raw.split(","):
        token = token.strip()

        if not token:
            continue

        number = (
            token if token in SCENARIOS
            else SCENARIO_ALIASES.get(token)
        )

        if number is None:
            invalid.append(token)
        else:
            choices.append(number)

    if not choices or invalid:
        raise SystemExit(
            "ERROR: Invalid option(s): "
            + (", ".join(invalid) if invalid else "(none given)")
        )

    # De-duplicate while preserving order.
    return list(dict.fromkeys(choices))


def parse_positions(raw):
    tokens = [token.strip() for token in raw.split(",") if token.strip()]

    invalid = [token for token in tokens if not token.isdigit()]

    if invalid:
        raise SystemExit("ERROR: Invalid position(s): " + ", ".join(invalid))

    return list(dict.fromkeys(int(token) for token in tokens))


def write_scenarios(chain, choices, positions, key_dir, export_dir):
    """Produce one output chain per selected scenario. Returns the count."""
    made = 0

    for choice in choices:
        targets = (
            positions if choice in POSITION_SCENARIOS and positions
            else [None]
        )

        for position in targets:
            label = SCENARIOS[choice] + (f"/int{position}" if position else "")

            try:
                out_dir, modified, extras = apply_scenario(
                    choice, chain, position, key_dir, export_dir
                )
            except SystemExit as exc:
                print(f"  [skip] {label}: {exc}")
                continue

            save_chain(modified, out_dir)

            for filename, content in extras.items():
                with open(os.path.join(out_dir, filename), "w") as handle:
                    handle.write(content)

            made += 1
            print(f"Saved: {out_dir}")

    return made


def main(argv=None):
    require_openssl()

    args = parse_args(argv)

    pkcs12 = Pkcs12Reader(args.p12_password)

    inputs = resolve_paths(args.paths)

    # Validate command-line selections now rather than after the chain has
    # been built, so a typo fails immediately.
    choices = (
        parse_scenarios(args.scenarios) if args.scenarios is not None
        else None
    )

    positions = (
        parse_positions(args.positions) if args.positions is not None
        else None
    )

    pin_path = resolve_pin_path(inputs)
    pinned_hash = read_pin(pin_path) if pin_path else None

    certs, _ = collect_material(inputs, pkcs12)

    if not certs:
        raise SystemExit(
            "ERROR: No certificates found "
            "(tried PEM, DER, PKCS#7 and PKCS#12)"
        )

    keys = collect_keys(inputs, pin_path, pkcs12)
    key_dir, key_count = write_key_dir(keys)

    try:
        print(
            f"\nLoaded {len(certs)} cert(s) and {key_count} key(s); "
            f"building chain..."
        )

        chain, candidate_count = find_trusted_chain(certs, pinned_hash)

        print(f"Found {candidate_count} possible path(s)")
        print("\nValid chain detected")

        if choices is None:
            print(SCENARIO_MENU)
            choices = parse_scenarios(
                input("Enter option(s) [e.g. 1,2,5 or all]: ")
            )

        if positions is None:
            if any(choice in POSITION_SCENARIOS for choice in choices):
                positions = parse_positions(
                    input("Positions for intermediate scenarios (e.g. 1,2): ")
                )
            else:
                positions = []

        made = write_scenarios(
            chain, choices, positions, key_dir, EXPORT_DIR
        )

        print(f"\nDone — {made} chain(s) generated")

    finally:
        # The key directory holds private key material; it never outlives
        # the run.
        shutil.rmtree(key_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
